import Head from "next/head";
import { useRouter } from "next/router";
import TemplateDefault from "../../components/template/Default";
import {
  ArrowLeftIcon,
  ArrowRightCircleIcon,
  CalendarDaysIcon,
  MapPinIcon,
  UserCircleIcon,
} from "@heroicons/react/24/outline";

export default function ScheduleDetail() {
  const router = useRouter();
  const { slug } = router.query;

  return (
    <>
      <Head>
        <title>Schedule Detail | PMI Semarang Regency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TemplateDefault
        withAppBarSpace={false}
        appBarLeft={
          <ArrowLeftIcon className="text-red-600 h-6 w-6 md:h-8 md:w-8" />
        }
        appBarRight={
          <UserCircleIcon className="text-red-600 h-6 w-6 md:h-8 md:w-8" />
        }
      >
        <section
          className="absolute top-0 left-0 w-full"
          id="local-blood-drive"
        >
          <img className="object-cover w-full" src="/xx5z7tz9.bmp" />
          <div className="relative w-full flex flex-col -top-6 left-0 rounded-2xl p-8 bg-white">
            <div className="flex flex-col mb-4">
              <span className="text-xl md:text-2xl">Nama Lokasi Jadwal</span>
              <span className="text-base md:text-lg">Semarang, Indonesia</span>
            </div>
            <div className="flex flex-col md:flex-row md:mt-2">
              <div className="md:basis-1/2 flex flex-row gap-2 md:gap-3 items-center mb-4">
                <div className="w-12 h-12 border-2 border-red-400 rounded-xl flex items-center justify-center">
                  <CalendarDaysIcon className="text-red-400 h-6 w-6" />
                </div>
                <div className="flex flex-col">
                  <span className="text-xs md:text-sm">20 December 2022</span>
                  <span className="text-base md:text-lg">
                    08:00 - 16:00 WIB
                  </span>
                </div>
              </div>
              <div className="md:basis-1/2 flex flex-row gap-2 md:gap-3 items-center mb-4">
                <div className="w-12 h-12 border-2 border-red-400 rounded-xl flex items-center justify-center">
                  <MapPinIcon className="text-red-400 h-6 w-6" />
                </div>
                <div className="flex flex-col">
                  <span className="text-xs md:text-sm">
                    Semarang, Indonesia
                  </span>
                  <span className="text-base md:text-lg">RS Citarum</span>
                </div>
              </div>
            </div>
          </div>
        </section>
        <div className="absolute w-full flex flex-col bottom-0 left-0 rounded-2xl p-8 bg-white">
          <button className="flex flex-row items-center justify-center gap-1 border-2 border-red-500 hover:bg-red-100 rounded-xl p-4">
            <span className="text-red-400 text-base md:text-lg">
              Go to Location
            </span>
            <ArrowRightCircleIcon className="text-red-400 h-6 w-6" />
          </button>
          <div className="w-full h-16 md:h-20"></div>
        </div>
      </TemplateDefault>
    </>
  );
}
