import Head from "next/head";
import BottomNavbar from "../../components/navbar/Bottom";
import AppNavbar from "../../components/navbar/App";
import ScheduleCard from "../../components/ScheduleCard";
import TemplateDefault from "../../components/template/Default";
import ArticleCard from "../../components/ArticleCard";
import {
  Bars2Icon,
  MagnifyingGlassIcon,
  UserCircleIcon,
} from "@heroicons/react/24/outline";

export default function Home() {
  return (
    <>
      <Head>
        <title>Schedules | PMI Semarang Regency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TemplateDefault
        withAppBarSpace={true}
        appBarLeft={
          <MagnifyingGlassIcon className="text-red-600 h-6 w-6 md:h-8 md:w-8" />
        }
        appBarRight={
          <UserCircleIcon className="text-red-600 h-6 w-6 md:h-8 md:w-8" />
        }
      >
        <section id="local-blood-drive">
          <h1 className="text-gray-700 text-2xl md:text-3xl mb-4 md:mb-6">
            Local Blood Drive
          </h1>
          <div className="flex flex-row gap-1">
            <span className="text-xs rounded-xl bg-red-200 p-1 px-3">
              Today
            </span>
            <span className="text-xs rounded-xl bg-white p-1 px-3">
              This Week
            </span>
            <span className="text-xs rounded-xl bg-white p-1 px-3">
              This Month
            </span>
          </div>
          <ScheduleCard
            location="RS Bhayangkara"
            month="Dec"
            date="14"
            time="08:00 - 16:00 WIB"
          />
          <ScheduleCard
            location="Puskesmas Tlogosari"
            month="Dec"
            date="14"
            time="08:00 - 16:00 WIB"
          />
          <ScheduleCard
            location="Poltekkes Semarang"
            month="Dec"
            date="14"
            time="08:00 - 16:00 WIB"
          />
        </section>
      </TemplateDefault>
    </>
  );
}
