import Head from "next/head";
import BottomNavbar from "../components/navbar/Bottom";
import AppNavbar from "../components/navbar/App";
import ScheduleCard from "../components/ScheduleCard";
import TemplateDefault from "../components/template/Default";
import ArticleCard from "../components/ArticleCard";
import {
  Bars2Icon,
  MagnifyingGlassIcon,
  UserCircleIcon,
} from "@heroicons/react/24/outline";

export default function Home() {
  return (
    <>
      <Head>
        <title>Articles | PMI Semarang Regency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TemplateDefault
        withAppBarSpace={true}
        appBarLeft={
          <MagnifyingGlassIcon className="text-red-600 h-6 w-6 md:h-8 md:w-8" />
        }
        appBarRight={
          <UserCircleIcon className="text-red-600 h-6 w-6 md:h-8 md:w-8" />
        }
      >
        <section id="local-blood-drive">
          <h1 className="text-gray-700 text-2xl md:text-3xl mb-4 md:mb-6">
            Articles
          </h1>
          <ArticleCard
            title="Judul Artikel Yang Harusnya Lebih Panjang"
            desc="Lorem ipsum dolor sit amet, ..."
          />
          <ArticleCard
            title="Judul Artikel Yang Harusnya Lebih Panjang"
            desc="Lorem ipsum dolor sit amet, ..."
          />
          <ArticleCard
            title="Judul Artikel Yang Harusnya Lebih Panjang"
            desc="Lorem ipsum dolor sit amet, ..."
          />
        </section>
      </TemplateDefault>
    </>
  );
}
