import Head from "next/head";
import BottomNavbar from "../components/navbar/Bottom";
import AppNavbar from "../components/navbar/App";
import ScheduleCard from "../components/ScheduleCard";
import TemplateDefault from "../components/template/Default";
import ArticleCard from "../components/ArticleCard";
import {
  Bars2Icon,
  MagnifyingGlassIcon,
  UserCircleIcon,
} from "@heroicons/react/24/outline";
import ForumCard from "../components/ForumCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Forums | PMI Semarang Regency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TemplateDefault
        withAppBarSpace={true}
        appBarLeft={
          <MagnifyingGlassIcon className="text-red-600 h-6 w-6 md:h-8 md:w-8" />
        }
        appBarRight={
          <UserCircleIcon className="text-red-600 h-6 w-6 md:h-8 md:w-8" />
        }
      >
        <section id="local-blood-drive">
          <h1 className="text-gray-700 text-2xl md:text-3xl mb-4 md:mb-6">
            Forums
          </h1>
          <div className="flex flex-row gap-1">
            <span className="text-xs rounded-xl bg-red-200 p-1 px-3">
              Most Useful
            </span>
            <span className="text-xs rounded-xl bg-white p-1 px-3">
              Latest
            </span>
          </div>
          <ForumCard
            author="Nama Orang"
            author_photo="/xx5z7tz9.bmp"
            author_time_posted="23 Hours ago"
            author_post="Lorem ipsum dolor sit amet, ... ?"
            best_answer="Nama Orang"
            best_answer_photo="/xx5z7tz9.bmp"
            best_answer_time_posted="2 Hours ago"
            best_answer_post="Lorem ipsum dolor sit amet, ..."
          />
        </section>
      </TemplateDefault>
    </>
  );
}
