import Head from "next/head";
import BottomNavbar from "../components/navbar/Bottom";
import AppNavbar from "../components/navbar/App";
import ScheduleCard from "../components/ScheduleCard";
import TemplateDefault from "../components/template/default";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | PMI Semarang Regency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TemplateDefault>
        <h1 className="text-gray-700 text-3xl md:text-5xl my-4 mt-6">
          Local Blood Drive
        </h1>
        <section id="local-blood-drive">
          <ScheduleCard
            location="Nama Lokasi"
            time="14 Desember 2022 08:00 - 16:00"
          />
          <ScheduleCard
            location="Nama Lokasi 2"
            time="14 Desember 2022 08:00 - 16:00"
          />
          <ScheduleCard
            location="Nama Lokasi 2"
            time="14 Desember 2022 08:00 - 16:00"
          />
          <ScheduleCard
            location="Nama Lokasi 2"
            time="14 Desember 2022 08:00 - 16:00"
          />
          <ScheduleCard
            location="Nama Lokasi 2"
            time="14 Desember 2022 08:00 - 16:00"
          />
          <ScheduleCard
            location="Nama Lokasi 2"
            time="14 Desember 2022 08:00 - 16:00"
          />
          <ScheduleCard
            location="Nama Lokasi 2"
            time="14 Desember 2022 08:00 - 16:00"
          />
          <ScheduleCard
            location="Nama Lokasi 2"
            time="14 Desember 2022 08:00 - 16:00"
          />
        </section>
        <h1 className="text-gray-700 text-3xl md:text-5xl my-4 mt-6">
          Articles
        </h1>
      </TemplateDefault>
    </>
  );
}
